vich_uploader:
    db_driver: orm

    mappings:
        content_images:
            uri_prefix: '%app.path.content_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.content_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove : true
            inject_on_load : true
            #delete_on_update : true